<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../plugins/paperformat-ai/src/PaperFormat.Domain/PaperFormat.Domain.csproj" />
  </ItemGroup>

</Project>
